//
//  HomeRouter.swift
//  DoRunDoRun
//
//  Created by Inho Choi on 9/13/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeRoutingLogic {
    func routeToOverallGoalList()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

final class HomeRouter: HomeRoutingLogic, HomeDataPassing {
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: Routing
    func routeToOverallGoalList() {
        let destinationVC = OverallGoalListViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToOverallGoalList(source: dataStore!, destination: &destinationDS)
        navigateToOverallGoalList(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    private func navigateToOverallGoalList(source: HomeViewController, destination: OverallGoalListViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    private func passDataToOverallGoalList(source: HomeDataStore, destination: inout OverallGoalListDataStore) {
        destination.overallGoal = source.overallGoal
    }
}
