//
//  HomeModels.swift
//  DoRunDoRun
//
//  Created by Inho Choi on 9/13/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum Home {
  
  // MARK: - Use cases
  
  enum LoadOverallGoal {
    struct Request { }
    struct Response {
      let overallGoal: OverallGoal
    }
    struct ViewModel {
      struct DisplayedGoal {
        let iconName: String
        let title: String
        let distance: String
        let time: String
        let pace: String
        let currentSession: String
        let totalSession: String
        let progress: Float
      }
      let displayedGoal: DisplayedGoal
    }
  }
  
  enum LoadSessionGoal {
    struct Request { }
    struct Response {
      let sessionGoal: SessionGoal
    }
    struct ViewModel {
        struct DisplayedSessionGoal {
          let title: String
          let subtitle: String
          let distance: String
          let time: String
          let pace: String
        }
        let displayedSessionGoal: DisplayedSessionGoal
    }
  }
}
