//
//  RunningInteractor.swift
//  DoRunDoRun
//
//  Created by Inho Choi on 9/13/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RunningBusinessLogic {
    func requestStartRunning(request: Running.StartRunning.Request)
}

protocol RunningDataStore {
    //var name: String { get set }
}

final class RunningInteractor: RunningDataStore {
    var presenter: RunningPresentationLogic?
    //var name: String = ""
    
    // MARK: Do something
    
}

extension RunningInteractor: RunningBusinessLogic {
    func requestStartRunning(request: Running.StartRunning.Request) {
        presenter?.presentStartRunning(response: .init())
    }
}
