//
//  RunningModels.swift
//  DoRunDoRun
//
//  Created by Inho Choi on 9/13/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Running {
    enum StartRunning {
        struct Request {}
        struct Response {}
        struct ViewModel {}
    }

    enum RunningUpdate {
        struct Request {}
        struct Response {
            let value: RunningSnapshot
            let startTime: Date
        }
        struct ViewModel { // TODO: 이거 나중에 ViewModel로 바꿀 것
            let value: RunningSnapshot
            let runningTimeString: String
            let metrics: RunningMetricsViewModel
        }
    }

    enum StopRunning {
        struct Request {}
        struct Response {}
        struct ViewModel {}
    }

    enum DrawRoute {
        struct Response {
            let coords: [RunningCoordinate]
        }
        struct ViewModel {
            let coords: [RunningCoordinate]
        }
    }
}
