//
//  ProfileInteractor.swift
//  DoRunDoRun
//
//  Created by Inho Choi on 9/13/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileBusinessLogic {
}

protocol ProfileDataStore {
    //var name: String { get set }
}

final class ProfileInteractor: ProfileDataStore {
    var presenter: ProfilePresentationLogic?
    //var name: String = ""
    
    // MARK: Do something
    
}

extension ProfileInteractor: ProfileBusinessLogic {
    
}
